#!/bin/sh
workdir=/usr/lib/python2.7/site-packages/vag-0.3-py2.7.egg/vag/
 
start() {
    cd $workdir
    /usr/bin/python vag.py &
    echo "VAG - Started."
}
 
stop() {
    pid=`ps -ef | grep '[p]ython vag.py' | awk '{ print $2 }'`
    echo $pid
    kill $pid
    sleep 2
    echo "VAG - Killed."
}
 
case "$1" in
  start)
    start
    ;;
  stop)
    stop   
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo "Usage: /etc/init.d/vag {start|stop|restart}"
    exit 1
esac
exit 0
